import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
decorations = "None"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0
