[font]
size = 13
normal = { family = "GeistMono Nerd Font Mono", style = "Regular" }

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 7, y = 0 }

[general]
import = ["~/.config/alacritty/theme.toml"]
